Enhance edge and vertex weights for `HyPar` optimizer
bsc-quantic/EinExprs.jl pull request #43
Opened 2023-11-02 15:10 UTC by jofrevalles

### Summary
This PR enhances the `HyPar` optimizer by adding two functions on its configuration that compute the weights for both `edges` and `vertices`. The functions `edge_weight_scaling` and `vertex_weight_scaling` enable the user to choose whether to apply a `log`, `linear`, `exp`, ... scaling into the size of the index (for the edges) or the product of the sizes of all the present indexes (for the vertices).

2023-11-02 15:31 UTC, mofeing requested changes

2023-11-02 15:31 UTC, mofeing commented on src/Optimizers/KaHyPar.jl
> +    vertex_weight_scaling::Function = (prod_size) -> 1000 * Int(round(log2(prod_size)))
1. Rename them to shorter names `edge_scaler`, `vertex_scaler`.
2. Try user the composition operator `∘` like in the `stop` field. This will make debugging much easier.

2023-11-02 15:31 UTC, mofeing commented on src/Optimizers/KaHyPar.jl
> +    edge_weights = map(ind -> config.edge_weight_scaling(size(path, ind)), inds)
Try using the compose operator `∘` and `Base.Fix1(size, path)`.

2023-11-02 15:31 UTC, mofeing commented on src/Optimizers/KaHyPar.jl
> +    vertex_weights = map(tensor -> config.vertex_weight_scaling(prod(size(tensor))), path.args)
Try using the compose operator `∘`. Can `prod(size(tensor))` be replaced for `length(tensor)` function?

2023-11-02 15:34 UTC, jofrevalles commented on src/Optimizers/KaHyPar.jl
> +    vertex_weights = map(tensor -> config.vertex_weight_scaling(prod(size(tensor))), path.args)
Yes, you are right.

2023-11-02 15:57 UTC, jofrevalles commented on src/Optimizers/KaHyPar.jl
> +    edge_weights = map(ind -> config.edge_weight_scaling(size(path, ind)), inds)
I don't think `Base.Fix1(size, path)` is necessary here, right?

2023-11-02 20:57 UTC, mofeing commented on src/Optimizers/KaHyPar.jl
> +    edge_weights = map(ind -> config.edge_weight_scaling(size(path, ind)), inds)
Generally it's better to use `Base.FixN` and `∘` over closures because of better optimization opportunities (closures are not _pure_ functions) and better stack traces (if something fails inside, closures are anonymous functions and thus will have random names).

Using closures is ok, but I tend to avoid closures in library code for these reasons.

2023-11-03 09:06 UTC, jofrevalles commented on src/Optimizers/KaHyPar.jl
> +    edge_weights = map(ind -> config.edge_weight_scaling(size(path, ind)), inds)
I have changed that so now we use `Base.Fix1`

2023-11-03 09:17 UTC, mofeing requested changes

2023-11-03 09:17 UTC, mofeing commented on src/Optimizers/KaHyPar.jl
> +    vertex_scaler::Function = (prod_size) -> 1000 * (Int ∘ round ∘ log2)(prod_size)
Just putting some `∘` but keeping the `->` does not remove the closure: it will still be a closure.

```suggestion
    edge_scaler::Function = *(1000) ∘ Int ∘ round ∘ log2
    vertex_scaler::Function = *(1000) ∘ Int ∘ round ∘ log2
```

2023-11-03 09:17 UTC, mofeing commented on src/Optimizers/KaHyPar.jl
> +        vertex_weights = map(config.vertex_scaler ∘ length, path.args)
```suggestion
        edge_weights = map(config.edge_scaler ∘ Base.Fix1(size, path), inds)
        vertex_weights = map(config.vertex_scaler ∘ length, path.args)
```

2023-11-03 09:19 UTC, jofrevalles commented on src/Optimizers/KaHyPar.jl
> +    vertex_scaler::Function = (prod_size) -> 1000 * (Int ∘ round ∘ log2)(prod_size)
Okey!

2023-11-03 12:10 UTC, jofrevalles commented
I think this could be already merged.

2023-11-03 12:16 UTC, mofeing approved these changes

2023-11-03 12:17 UTC, merged